### ISSUE TITLE
Concatenating trajectories in tutorial

### ISSUE THREAD

**Issue by andresilvapimentel** [membrane-systems/PCAlipids#21]
I am trying to run the tutorial by running the command:

!python3 pcalipids.py concat -f trajectory.xtc -t structure.pdb -l DOPC

I got the error message:
Traceback (most recent call last):
  File "pcalipids.py", line 326, in <module>
    main(args)
  File "pcalipids.py", line 322, in main
    main(*params)
  File "/content/PCAlipids/scr/con_traj.py", line 44, in main
    lipid_resname = lipid_resname, stride = stride, sf = sf, ef = ef)
  File "/content/PCAlipids/scr/con_traj.py", line 13, in load_traj
    topol = md.load(traj_top).topology
  File "/usr/local/lib/python3.7/dist-packages/mdtraj/core/trajectory.py", line 433, in load
    value = loader(filename, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mdtraj/formats/pdb/pdbfile.py", line 153, in load_pdb
    with PDBTrajectoryFile(filename, standard_names=standard_names) as f:
  File "/usr/local/lib/python3.7/dist-packages/mdtraj/formats/pdb/pdbfile.py", line 269, in __init__
    self._read_models()
  File "/usr/local/lib/python3.7/dist-packages/mdtraj/formats/pdb/pdbfile.py", line 563, in _read_models
    self._topology.create_disulfide_bonds(self.positions[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

Could you help me to find the error, please?

**Comment by pbuslaev** [comment]
Hi, could you please run pcalipids and pcalipids concat without any options and share the output please?
